### ISSUE TITLE
Tab doesn't appear

### ISSUE THREAD

**Issue by aruhier** [KoKuToru/nautilus-snapper-extension#1]
Hello,
I wanted to test your plugin on ArchLinux, but the tab "Snapper" doesn't appear is nautilus.
I'm running on btrfs, and my btrfs pull is split like that:
    - home with a subvolume .snapshots, made by snapper
    - root with a subvolume .snapshots, made by snapper
    - var

Permissions of my .snapshots directories are setup with ACL.

**Comment by KoKuToru** [comment]
Should work now, let me know if it works

**Comment by aruhier** [comment]
Yeah it works, thank you !
